# Generated by Django 5.2.14 on 2026-05-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="drop_address",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="delivery",
            name="pickup_address",
            field=models.TextField(default=""),
        ),
    ]
