# Generated by Django 5.2.14 on 2026-05-26 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("BIKE", "BIKE"),
                            ("CAR", "CAR"),
                            ("SCOTTER", "SCOTTER"),
                        ],
                        max_length=20,
                    ),
                ),
                ("vehicle_number", models.CharField(max_length=50, unique=True)),
                ("liscence_number", models.CharField(max_length=100, unique=True)),
                ("is_online", models.BooleanField(default=False)),
                ("current_latitude", models.FloatField(blank=True, null=True)),
                ("current_longitude", models.FloatField(blank=True, null=True)),
                ("rating", models.FloatField(default=5.0)),
                ("total_deliveries", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
